### ISSUE TITLE
I need to understand the legal requirement for making services accessible

### ISSUE THREAD

**Issue by accessiblewebuk** [alphagov/accessibility-guidance#12]
"Understands that for a website to be considered legally accessible it will need to meet WCAG 2.0 AA and have included people with disabilities in design and usability testing "

As far as I know the Equality Act doesn't specify any of this, and there is no definition of what is legally accessible, other than the reasonable adjustments test.

**Comment by LJWatson** [comment]
You're right. The Equality Act simply requires that services are accessible. It doesn't define what accessibility means in that context.

Where did that quote come from?

**Comment by aduggin** [comment]
I got this from a couple of sources.

'Disabled access to websites under UK law' by out-law.com
http://www.out-law.com/page-330

"The best way to satisfy the legal requirement is to have your website tested by disabled users. This should ideally be done through allowing your website to be tested by a group of users with different disabilities, such as motor and cognitive disabilities, blindness and other forms of visual impairment.  Evidence of successful tests by disabled users could be invaluable in the event of any legal challenge over your website's accessibility."

And

"The World Wide Web Consortium (W3C), the international organisation concerned with providing standards for the web, publishes the Web Content Accessibility Guidelines 2.0 (WCAG 2.0) which are a good indicator of what standard the courts would reasonably expect businesses to follow to ensure that their websites are accessible in accordance with the EQA."

Similar inform is provided in BS 8878:2010 (Web accessibility – Code of practice)

"There is a misconception that conforming to a particular Level of WCAG will make web products legally compliant. It is true that a web product conforming to Level AA of WCAG is unlikely to be the subject of a legal challenge; but neither the Equality Act nor the DDA makes any reference to WCAG or any other web guidelines.

Only a court can decide whether a web product complies with the legislation or not. The key question for a court is likely to be whether disabled users can access and use the web product without unreasonable difficulty. Time, inconvenience and effort might be relevant factors in gauging whether there is unreasonable difficulty.

The best evidence of a compliant web product is likely to be evidence of successful user testing that involved disabled participants. Frequent testing and the involvement of participants with different disability profiles will strengthen that evidence.

Evidence that a web product conforms to WCAG Level A or higher will be useful and could be influential – but it is likely to be less influential before a court or tribunal than evidence of successful user testing."
