### ISSUE TITLE
Describing audits

### ISSUE THREAD

**Issue by LJWatson** [alphagov/accessibility-guidance#19]
In [Getting an audit](https://github.com/alphagov/accessibility-guidance/wiki/Getting-an-accessibility-audit---version-for-fact-check) the words "small" and "full" are used to describe different audits. There is no concept of a "small" audit because the only thing that changes is the size of the sample to be tested. So whether the sample is 50 patterns from a library, 10 pages from a website, or 25 steps from a transactional service, the audit is always "full" because the sample is always tested against the complete set of WCAG SC.

Suggest using phrases like "pattern library audit", beta audit" etc. instead of these words.

**Comment by spencerball** [comment]
Thanks Leonie. Al raised a similar point last week when he checked the content.

We've opted to use 'Early audit' and 'Later audit' for the version we're going to test with users. We want to emphasise that they are two discrete activities, and that there's a chronology to them. Al's also keen that we emphasise that teams should do the first audit as early as possible in their beta phase (which 'Early audit' should help do).

I hope this sounds ok to you, but please let me know if not.

**Comment by LJWatson** [comment]
I've just realised there is no mention of an audit after beta? Service teams will need to have their service audited at least once more before it goes live - in order to make sure that changes made to the service during beta have not introduced accessibility problems. It's the outcome of this audit that would feed into the service assessment for go-live.

**Comment by spencerball** [comment]
@LJWatson I've tweaked the line under ### Later audit as follows:

Get another audit before your beta [service assessment](/service-manual/service-assessments/how-service-assessments-work). Give yourself enough time to fix any problems found by the audit - you’ll need to get a re-test to show you’ve fixed them.

We also include re-testing as a distinct activity under ## What to ask for

Do you think that's sufficient?

**Comment by LJWatson** [comment]
That looks good to me.
