### ISSUE TITLE
Standard: Can we be any clearer about what perceivable means?

### ISSUE THREAD

**Issue by aduggin** [alphagov/accessibility-guidance#3]
Can we do more to explain what Perceivable means?
Would it be useful to convey some of the following in a more succinct way?

For content to be perceived by someone it needs to be available to at least one of the following senses: sight, hearing, touch.

For someone that has low vision this means they can see it - which requires the content to be large enough and the colour contrast to be high enough. As a baseline with want text to have a good colour contrast and for text to be a good size - so that as many people as possible can see it without having to adjust it. For people where this is not sufficient they need to be able to either customise the interface in the browser (change the font size and/or the colour) or by using software such as screen magnification. These will only work if a web content has been implemented in such a way that it is compatible with browser settings (and a user knows how to change the browser settings) and compatible with screen magnification software.

For someone that can't see this means that the content needs to be available to them as sound or touch. This is achieved by using software that converts text to sound ( a screen reader) and to touch (electronic braille). This will only work if the web content has been implemented in such a way this it is compatible with the assistive technology, for example all text is available as text in the HTML, that the text is in correct order in the HTML, and that correct HTML elements have been used to markup the content, and best practice has been followed to convey information about the layout of a page, content, forms and tabular information.

**Comment by accessiblewebuk** [comment]
touch isn't just braille but should also any kind of haptic feedback (which is becoming more common)
