### ISSUE TITLE
Standard: things to do to be operable

### ISSUE THREAD

**Issue by aduggin** [alphagov/accessibility-guidance#5]
A "skip to content" link only needs to be provided if there are links that need to be bypassed. If there is a "skip to content" link it needs to work in all browsers (so requires adding tabindex="-1" for it to work in chrome and safari).

Is it worth calling out the using standard form controls with good form markup will mean that your forms are likely to just work in screen readers and speech recognition software. Building your own interface controls requires lots of testing to ensure that they work in all assistive technologies.

**Comment by LJWatson** [comment]
I think it depends whether we want this doc to be intro level, or whether we want to get into explaining things and providing techniques. My understanding was that it was the former... either is fine, but think we should probably agree what it is we're trying to create.

**Comment by aduggin** [comment]
I thinking it would be good to create both - one that is a succinct strip down intro (like we have now) and another that provides a little more information. Angela can then do some user researcher and find out which approach people find more useful. I think we'll learn more by testing with 2 versions rather than just one.
