### ISSUE TITLE
Standard: things to do to be understandable

### ISSUE THREAD

**Issue by aduggin** [alphagov/accessibility-guidance#6]
Dynamic information that is communicated visually (such as an error message or alert, that something is selected, or a progress indicator) also needs to be made available to a screen reader.

**Comment by accessiblewebuk** [comment]
doesn't that come under robust, rather than understandable?

**Comment by LJWatson** [comment]
Think @accessiblewebuk is correct.

**Comment by accessiblewebuk** [comment]
"Do not make big changes to content without people being aware of it" - is that referring to static or dynamic changes (or both)?

**Comment by accessiblewebuk** [comment]
"form controls" is more generic than "form fields" - I wouldn't describe a select box as a form field for example.
