### ISSUE TITLE
Standard: things to do to be robust

### ISSUE THREAD

**Issue by aduggin** [alphagov/accessibility-guidance#7]
I think 'Make sure the name, role and state of every feature can be identified' needs more explanation - won't make much sense to most people

Robust is about making sure that a website/service work in the technologies that people are using.  Would be good to call out that this means that they need to work in screen readers, speech recognition software, screen magnification software and literacy software and to link to our assistive technology (AT) and Browser matrix (when we have it) and any guidance we have about AT testing. Should we also link to the the [browser support guidelines in the service manual](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices)?

**Comment by aduggin** [comment]
Where we say that html needs to be valid let's link to a validator: https://validator.w3.org/

**Comment by accessiblewebuk** [comment]
I think the browser support guidelines should be linked to - I also think that document should incorporate the assistive technology details as well (particularly as it says "Your service must be universally accessible.")

As discussed at the away day, when it comes to the AT matrix I think we need to be focusing on the most popular software and versions and possibly combinations of AT and browser, so for example several recent versions of JAWS are probably more important than any version of Supernova.

**Comment by LJWatson** [comment]
My hesitation with calling out those things is that it puts an AT slant on this principle - which is about all kinds of tech, not just assistive tech.

**Comment by accessiblewebuk** [comment]
Sorry, that is me digressing, just thinking out loud, I don't mean we should include all the AT stuff in the main document.

**Comment by accessiblewebuk** [comment]
If it is more than intro level  documentation we should add something about identifying things correctly through ARIA particularly for examples like links displayed as buttons.
