### ISSUE TITLE
standard: Who should think about it?

### ISSUE THREAD

**Issue by aduggin** [alphagov/accessibility-guidance#8]
We can improve these to match the language that is used in the service manual for roles in service delivery teams - and the roles that are expected to be in teams

* Product and service managers
* Delivery managers
* User researchers
* Content designers/managers
* Designers (service designers, interaction designer and visual designers)
* Developers
* Testers

**Comment by accessiblewebuk** [comment]
We need to take into account that non-GDS teams may use different terms for some of these and also have other roles for example Business Analyst

**Comment by LJWatson** [comment]
The list has been updated in what is now wcag.md. This <a href="https://github.com/alphagov/accessibility-guidance/commit/4828a3ee5e5ffdd1658d806e700625ba1d0a0466">commit</a> has the changes.
